version: '3.8'
services:

  frontend:
    build: .
    container_name: frontend-container
    command: ["nginx", "-g", "daemon off;"]
    restart: always
    ports:
      - "80:80"
    networks:
      my-network:
        ipv4_address: 172.18.0.4

networks:
  my-network:
    driver: bridge
    external: true
      

